# Generated by Django 2.0.4 on 2018-08-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='本金')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='收益')),
                ('unit', models.IntegerField(choices=[(0, '人民币'), (1, '美元')], default=0, verbose_name='资产单位')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.User')),
            ],
            options={
                'verbose_name': '投资表',
                'db_table': 'investment',
            },
        ),
    ]
