# Generated by Django 2.0.4 on 2018-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='unit',
            field=models.IntegerField(choices=[(0, '人民币'), (1, '美元')], default=0, verbose_name='资产单位'),
        ),
    ]
