# Generated by Django 2.0.4 on 2018-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '不详'), (1, '男'), (2, '女')], default=0, null=True, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最近活跃时间')),
                ('follow_projects', models.ManyToManyField(to='project.Project', verbose_name='预约产品')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
